// AI-ASSISTED: generated by scripts/gen_contracts.py from api/src/quiz/contracts. Do not edit; run `make contracts`.

/**
 * Wire protocol v1 of the real-time quiz (docs/spec/protocol.md).
 */
export type Protocol = ClientMessage | ServerMessage;
export type ClientMessage = Join | Next | Answer | Ping | Resync | GetLeaderboard;
export type ServerMessage =
  | Leaderboard
  | QuizEnded
  | Joined
  | Question
  | AnswerResult
  | RankUpdate
  | LeaderboardPage
  | Snapshot
  | Finished
  | Pong
  | ProtocolError;
export type ErrorCode =
  | "INVALID_MESSAGE"
  | "UNSUPPORTED_TYPE"
  | "UNSUPPORTED_VERSION"
  | "MESSAGE_TOO_LARGE"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "QUIZ_NOT_FOUND"
  | "NOT_JOINED"
  | "QUESTION_NOT_OPEN"
  | "ALREADY_ANSWERED"
  | "RATE_LIMITED"
  | "SESSION_REPLACED"
  | "UNAVAILABLE"
  | "INTERNAL"
  | "QUIZ_ENDED"
  | "INVALID_STATE";

export interface Join {
  v: 1;
  type: "join";
  quizId: string;
  displayName: string;
}
export interface Next {
  v: 1;
  type: "next";
  questionIndex: number;
}
export interface Answer {
  v: 1;
  type: "answer";
  questionIndex: number;
  choiceIndex: number;
  submissionId: string;
}
export interface Ping {
  v: 1;
  type: "ping";
}
export interface Resync {
  v: 1;
  type: "resync";
  lastSeq: number;
}
export interface GetLeaderboard {
  v: 1;
  type: "get_leaderboard";
  offset: number;
  limit: number;
}
export interface Leaderboard {
  v: 1;
  type: "leaderboard";
  seq: number;
  rebase: boolean;
  playerCount: number;
  onlineCount: number;
  /**
   * @maxItems 200
   */
  entries: Entry[];
}
export interface Entry {
  rank: number;
  userId: string;
  displayName: string;
  score: number;
}
export interface QuizEnded {
  v: 1;
  type: "quiz_ended";
  seq: number;
  playerCount: number;
  /**
   * @maxItems 50
   */
  entries: Entry[];
  you: You | null;
}
export interface You {
  rank: number;
  score: number;
}
export interface Joined {
  v: 1;
  type: "joined";
  atSeq: number;
  quizId: string;
  userId: string;
  displayName: string;
  questionCount: number;
  timeLimitMs: number;
  quizRemainingMs: number;
  cursor: number;
  cursorOpen: boolean;
  finished: boolean;
  score: number;
}
export interface Question {
  v: 1;
  type: "question";
  atSeq: number;
  questionIndex: number;
  questionId: string;
  prompt: string;
  /**
   * @minItems 4
   * @maxItems 4
   */
  choices: [string, string, string, string];
  timeLimitMs: number;
  remainingMs: number;
}
export interface AnswerResult {
  v: 1;
  type: "answer_result";
  atSeq: number;
  questionIndex: number;
  submissionId: string;
  choiceIndex: number;
  correctChoiceIndex: number;
  correct: boolean;
  late: boolean;
  pointsAwarded: number;
  score: number;
}
export interface RankUpdate {
  v: 1;
  type: "rank_update";
  atSeq: number;
  rank: number;
  score: number;
  playerCount: number;
}
export interface LeaderboardPage {
  v: 1;
  type: "leaderboard_page";
  atSeq: number;
  offset: number;
  playerCount: number;
  final: boolean;
  /**
   * @maxItems 200
   */
  entries: Entry[];
}
export interface Snapshot {
  v: 1;
  type: "snapshot";
  atSeq: number;
  status: "open" | "ended";
  playerCount: number;
  onlineCount: number;
  /**
   * @maxItems 200
   */
  entries: Entry[];
  you: You | null;
}
export interface Finished {
  v: 1;
  type: "finished";
  atSeq: number;
  score: number;
  rank: number;
  playerCount: number;
}
export interface Pong {
  v: 1;
  type: "pong";
  seq: number | null;
}
export interface ProtocolError {
  v: 1;
  type: "error";
  code: ErrorCode;
  message: string;
  requestType: string | null;
}
