#!/usr/bin/env python3
# AI-ASSISTED: writes the JSON Schema and the client TypeScript types from the Pydantic wire models.
"""Regenerate the generated contract files from ``quiz.contracts``.

    gen_contracts.py    write contracts/schema/protocol.json and web/src/protocol/types.generated.ts

The output is deterministic, so ``make contracts && git diff --exit-code`` finds drift.
"""

import json
import subprocess
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaMode
from pydantic_core import CoreSchema

from quiz.contracts.messages import ClientMessage, ServerMessage

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "contracts" / "schema" / "protocol.json"
TYPES = ROOT / "web" / "src" / "protocol" / "types.generated.ts"
BANNER = (
    "// AI-ASSISTED: generated by scripts/gen_contracts.py from api/src/quiz/contracts."
    " Do not edit; run `make contracts`."
)


class _NoFieldTitles(GenerateJsonSchema):
    """Leave out per-field titles, so the TypeScript output has no alias per field."""

    def field_title_should_be_set(self, schema: CoreSchema) -> bool:  # noqa: ARG002
        return False


def build_schema() -> dict[str, Any]:
    """Return one JSON Schema whose ``$defs`` hold every message and both unions."""
    inputs: list[tuple[str, JsonSchemaMode, TypeAdapter[Any]]] = [
        (name, "serialization", TypeAdapter(union))
        for name, union in (("ClientMessage", ClientMessage), ("ServerMessage", ServerMessage))
    ]
    _, schema = TypeAdapter.json_schemas(inputs, title="Protocol", schema_generator=_NoFieldTitles)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": schema["title"],
        "description": "Wire protocol v1 of the real-time quiz (docs/spec/protocol.md).",
        "oneOf": [{"$ref": f"#/$defs/{name}"} for name, _, _ in inputs],
        "$defs": dict(sorted(schema["$defs"].items())),
    }


def write_types(schema_path: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [  # noqa: S607
            "pnpm",
            "--silent",
            "-C",
            str(ROOT / "web"),
            "exec",
            "json2ts",
            "--input",
            str(schema_path),
            "--output",
            str(out),
            "--unreachableDefinitions",
            "--additionalProperties=false",
            "--bannerComment",
            BANNER,
        ],
        check=True,
    )


def main() -> None:
    SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA.write_text(json.dumps(build_schema(), indent=2, ensure_ascii=False) + "\n")
    write_types(SCHEMA, TYPES)


if __name__ == "__main__":
    main()
