#!/usr/bin/env python3
# AI-ASSISTED: writes the JSON Schema and the client TypeScript types from the Pydantic wire models.
"""Regenerate the generated contract files from ``quiz.contracts``.

    gen_contracts.py           write contracts/schema/protocol.json and
                               web/src/protocol/types.generated.ts
    gen_contracts.py --check   regenerate, then exit 1 if a generated file differs from git
                               (changed, deleted or untracked)

The output is deterministic, so ``--check`` (a step of ``make check``) finds drift.
"""

import argparse
import json
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaMode
from pydantic_core import CoreSchema

from quiz.contracts.messages import CLIENT_ADAPTER, SERVER_ADAPTER

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "contracts" / "schema" / "protocol.json"
TYPES = ROOT / "web" / "src" / "protocol" / "types.generated.ts"
GENERATED = (SCHEMA, TYPES)
BANNER = (
    "// Generated by scripts/gen_contracts.py from api/src/quiz/contracts."
    " Do not edit; run `make contracts`."
)


class _NoFieldTitles(GenerateJsonSchema):
    """Leave out per-field titles, so the TypeScript output has no alias per field."""

    def field_title_should_be_set(self, schema: CoreSchema) -> bool:  # noqa: ARG002
        return False


def build_schema() -> dict[str, Any]:
    """Return one JSON Schema whose ``$defs`` hold every message and both unions."""
    # The codec validates with these adapters, so the published schema is the parser's.
    inputs: list[tuple[str, JsonSchemaMode, TypeAdapter[Any]]] = [
        ("ClientMessage", "serialization", CLIENT_ADAPTER),
        ("ServerMessage", "serialization", SERVER_ADAPTER),
    ]
    _, schema = TypeAdapter.json_schemas(inputs, title="Protocol", schema_generator=_NoFieldTitles)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": schema["title"],
        "description": "Wire protocol v1 of the real-time quiz (docs/spec/protocol.md).",
        "oneOf": [{"$ref": f"#/$defs/{name}"} for name, _, _ in inputs],
        "$defs": dict(sorted(schema["$defs"].items())),
    }


def write_types(schema_path: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [  # noqa: S607
            "pnpm",
            "--silent",
            "-C",
            str(ROOT / "web"),
            "exec",
            "json2ts",
            "--input",
            str(schema_path),
            "--output",
            str(out),
            "--unreachableDefinitions",
            "--additionalProperties=false",
            "--bannerComment",
            BANNER,
        ],
        check=True,
    )


def drift(root: Path, paths: Sequence[Path]) -> list[str]:
    """Return the ``git status`` lines of ``paths``: changed, deleted or untracked files."""
    result = subprocess.run(
        [  # noqa: S607
            "git",
            "-C",
            str(root),
            "status",
            "--porcelain",
            "--untracked-files=all",
            "--",
            *(str(path) for path in paths),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.splitlines()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if a generated file differs from git"
    )
    args = parser.parse_args(argv)
    SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA.write_text(json.dumps(build_schema(), indent=2, ensure_ascii=False) + "\n")
    write_types(SCHEMA, TYPES)
    if args.check and (lines := drift(ROOT, GENERATED)):
        print("generated contracts differ from git; run `make contracts`:", file=sys.stderr)
        print("\n".join(lines), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
