// AI-ASSISTED: every piece of UI copy in one module, so a translation can be added later.
export const strings = {
  appName: 'Vocab Quiz',
  join: {
    title: 'Real-time vocabulary quiz',
    quizIdLabel: 'Quiz ID',
    quizIdHint: 'For example VOCAB-42',
    nameLabel: 'Your name',
    submit: 'Join',
    joining: 'Joining…',
    quizIdInvalid: 'Use 3–16 letters, digits or dashes, like VOCAB-42',
    nameRequired: 'Enter your name',
    nameTooLong: 'Use at most 32 characters',
    notFound: 'No quiz with this ID',
  },
  quiz: { title: (quizId: string) => `Quiz ${quizId}` },
  leaderboard: {
    title: 'Leaderboard',
    counts: (players: number, online: number) => `${players} players · ${online} online`,
    updating: 'Updating…',
    you: '(you)',
    showAll: 'Show all players',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    range: (from: number, to: number, total: number) => `Players ${from}–${to} of ${total}`,
    asOf: (seq: number) => `As of update ${seq}`,
    final: 'Final standings',
  },
  notFound: {
    title: 'Page not found',
    body: 'There is no page at this address.',
    home: 'Back to the start',
  },
} as const
