// AI-ASSISTED: every piece of UI copy in one module, so a translation can be added later.
export const strings = {
  appName: 'Vocab Quiz',
  join: {
    title: 'Real-time vocabulary quiz',
    quizIdLabel: 'Quiz ID',
    quizIdHint: 'For example VOCAB-42',
    nameLabel: 'Your name',
    submit: 'Join',
    submitEnded: 'See results',
    joining: 'Joining…',
    checking: 'Looking up the quiz…',
    quizIdInvalid: 'Use 3–16 letters, digits or dashes, like VOCAB-42',
    nameRequired: 'Enter your name',
    nameTooLong: 'Use at most 32 characters',
    notFound: 'No quiz with this ID',
    ended: 'This quiz has ended. You can still see the final results.',
    preview: {
      open: 'Open',
      ended: 'Ended',
      questions: (n: number) => (n === 1 ? '1 question' : `${n} questions`),
      players: (n: number) => (n === 1 ? '1 player' : `${n} players`),
    },
  },
  quiz: {
    title: (quizId: string) => `Quiz ${quizId}`,
    progress: (k: number, n: number) => `Question ${k} of ${n}`,
    score: (score: number) => `Score ${score}`,
    rank: (rank: number, players: number) => `#${rank} of ${players}`,
    intro: (n: number, seconds: number) => `${n} questions, ${seconds} seconds each.`,
    rule: 'Correct answers score 100–150 points, more when faster; wrong or late answers score 0.',
    start: 'Start',
    continue: 'Continue',
    secondsLeft: (seconds: number) => `${seconds} seconds left`,
    checking: 'Checking…',
    timeUp: "Time's up: an answer now scores 0.",
    waiting: 'Waiting for the connection…',
    skip: 'Skip',
  },
  leaderboard: {
    title: 'Leaderboard',
    counts: (players: number, online: number) => `${players} players · ${online} online`,
    updating: 'Updating…',
    you: '(you)',
    showAll: 'Show all players',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    range: (from: number, to: number, total: number) => `Players ${from}–${to} of ${total}`,
    asOf: (seq: number) => `As of update ${seq}`,
    final: 'Final standings',
  },
  results: {
    finished: 'You finished!',
    provisional: 'Provisional',
    rank: (rank: number, players: number) => `Rank #${rank} of ${players}`,
    canChange: (time: string) => `Your rank can still change until the quiz ends in ${time}.`,
    points: (score: number) => `${score} points`,
    title: 'Final results',
    placed: (rank: number, players: number) => `You placed #${rank} of ${players}`,
  },
  notFound: {
    title: 'Page not found',
    body: 'There is no page at this address.',
    home: 'Back to the start',
  },
} as const
