// AI-ASSISTED: every piece of UI copy in one module, so a translation can be added later.
const players = (n: number): string => (n === 1 ? '1 player' : `${n} players`)
const questions = (n: number): string => (n === 1 ? '1 question' : `${n} questions`)
const seconds = (n: number): string => (n === 1 ? '1 second' : `${n} seconds`)

export const strings = {
  appName: 'Vocab Quiz',
  skipLink: 'Skip to content',
  join: {
    title: 'Real-time vocabulary quiz',
    quizIdLabel: 'Quiz ID',
    quizIdHint: 'For example VOCAB-42-7K3Q',
    nameLabel: 'Your name',
    submit: 'Join',
    submitEnded: 'See results',
    joining: 'Joining…',
    checking: 'Looking up the quiz…',
    quizIdInvalid: 'Use 3–16 letters, digits or dashes, like VOCAB-42-7K3Q',
    nameRequired: 'Enter your name',
    nameTooLong: 'Use at most 32 characters',
    nameInvisible: 'Use at least one visible character',
    nameControl: 'Remove tabs, line breaks and other control characters',
    notFound: 'No quiz with this ID',
    failed: 'Could not join, try again',
    resume: (quizId: string) => `Resume quiz ${quizId}`,
    ended: 'This quiz has ended. You can still see the final results.',
    hostPrompt: 'Running a class or a game night?',
    host: 'Host a quiz',
    preview: {
      open: 'Open',
      ended: 'Ended',
      questions,
      players,
    },
  },
  host: {
    title: 'Host a quiz',
    intro: 'Pick a question set. You get a quiz ID, a link and a QR code to share; players join on their own devices.',
    banksLabel: 'Question sets',
    loading: 'Loading question sets…',
    questions,
    pick: 'Host',
    creating: 'Creating…',
    retry: 'Try again',
    off: 'This server does not offer public hosting.',
    full: 'Every public quiz slot is in use. Try again in a few minutes.',
    rateLimited: (wait: string) => `You started several quizzes in a row. Try again in ${wait}.`,
    seconds,
    minutes: (n: number) => (n === 1 ? '1 minute' : `${n} minutes`),
    invalid: 'That question set is no longer available. Pick another one.',
    error: 'Could not reach the server. Check your connection and try again.',
    ready: 'Your quiz is open',
    quizIdLabel: 'Quiz ID',
    closesAt: (time: string) => `Open until ${time}`,
    linkLabel: 'Player link',
    copy: 'Copy link',
    copied: 'Link copied',
    copyFailed: 'Could not copy; select the link and copy it.',
    qrLabel: (url: string) => `QR code of the player link ${url}`,
    players: (n: number) => (n === 1 ? '1 player joined' : `${n} players joined`),
    joinAsPlayer: 'Join as a player',
    newTab: '(opens in a new tab)',
    end: 'End quiz',
    confirmEnd: 'End the quiz for everyone? Players see the final results and cannot answer any more.',
    confirm: 'End it now',
    keepOpen: 'Keep it open',
    ending: 'Ending…',
    endFailed: 'Could not end the quiz, try again.',
    forbidden: 'This tab can no longer end the quiz.',
    ended: (quizId: string) => `Quiz ${quizId} has ended`,
    endedBody: 'Players can still open the link to see the final results.',
    openLink: 'Open the player link',
    again: 'Host another quiz',
  },
  quiz: {
    title: (quizId: string) => `Quiz ${quizId}`,
    tab: 'Quiz',
    progress: (k: number, n: number) => `Question ${k} of ${n}`,
    score: (score: number) => `Score ${score}`,
    rank: (rank: number, players: number) => `#${rank} of ${players}`,
    announceRank: (rank: number, players: number) => `Rank ${rank} of ${players}`,
    intro: (count: number, limit: number) => `${questions(count)}, ${seconds(limit)} each.`,
    quizLeft: (time: string) => `${time} left in the quiz`,
    rule: 'Correct answers score 100–150 points, more when faster; wrong or late answers score 0.',
    start: 'Start',
    continue: 'Continue',
    loading: 'Loading the question…',
    secondsLeft: (left: number) => `${seconds(left)} left`,
    timeLeft: (seconds: number) => `${seconds} s left`,
    checking: 'Checking…',
    timeUp: "Time's up: an answer now scores 0.",
    waiting: 'Waiting for the connection…',
    skip: 'Skip',
    correct: 'Correct',
    wrong: 'Wrong',
    correctAnswer: 'Correct answer',
    late: 'Too late: 0 points',
    points: (n: number) => `+${n} points`,
    bonus: (n: number) => `including a speed bonus of +${n}`,
    nextQuestion: 'Next question',
    seeResult: 'See my result',
    announceCorrect: (points: number) => `Correct, plus ${points} points`,
    announceWrong: (answer: string) => `Wrong, the answer was “${answer}”`,
    announce: (result: string, score: number) => `${result}. Score ${score}.`,
  },
  connection: {
    connecting: 'Connecting…',
    reconnecting: 'Reconnecting…',
    resyncing: 'Updating…',
    closed: 'Disconnected. Reload the page to try again.',
    busy: 'Server busy, retrying',
  },
  /** The error codes that show a short message; every other code shows none, the client recovers by itself (UI spec §4.3). */
  errors: {
    ALREADY_ANSWERED: 'That question was already answered; your first answer stands.',
    QUESTION_NOT_OPEN: 'That question is closed; loading the current one.',
    RATE_LIMITED: 'Too many requests; trying again in a second.',
    QUIZ_ENDED: 'The quiz has ended.',
  },
  /** The blocking cards, by the store's `blocked` state (UI spec §3.7). */
  blocked: {
    replaced: { title: 'This quiz is open in another tab.', action: 'Use this tab' },
    version: { title: 'A new version is available.', action: 'Reload' },
    policy: { title: "Can't connect to this quiz.", action: 'Reload' },
    unreachable: { title: "Still can't connect.", action: 'Try again' },
    gone: { title: 'This quiz is no longer available.', action: 'Back to join' },
  },
  leaderboard: {
    title: 'Leaderboard',
    counts: (count: number, online: number) => `${players(count)} · ${online} online`,
    updating: 'Updating…',
    you: '(you)',
    showAll: 'Show all players',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    range: (from: number, to: number, total: number) => `Players ${from}–${to} of ${total}`,
    loading: 'Loading players…',
    final: 'Final standings',
  },
  results: {
    finished: 'You finished!',
    provisional: 'Provisional',
    rank: (rank: number, players: number) => `Rank #${rank} of ${players}`,
    rankLive: (rank: number, players: number) => `Rank ${rank} of ${players}`,
    canChange: (time: string) => `Your rank can still change until the quiz ends in ${time}.`,
    points: (score: number) => `${score} points`,
    title: 'Final results',
    placed: (rank: number, players: number) => `You placed #${rank} of ${players}`,
    noPlayers: 'No one played this quiz.',
  },
  notFound: {
    title: 'Page not found',
    body: 'There is no page at this address.',
    home: 'Back to the start',
  },
} as const
